# Generated by Django 4.0.3 on 2022-03-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_bird_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birdhouse',
            old_name='color',
            new_name='house_type',
        ),
    ]
