# Generated by Django 4.0.3 on 2022-03-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_color_birdhouse_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='gender',
            field=models.CharField(choices=[('f', 'female'), ('m', 'male')], max_length=10),
        ),
    ]
