# Generated by Django 4.0.3 on 2022-03-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_birdhouse_bird_birdhouses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bird',
            old_name='Birdhouses',
            new_name='birdhouses',
        ),
    ]
